### ISSUE TITLE
Can't sign messages using hardware wallet (trezor)

### ISSUE THREAD

**Issue by slingncrypto** [00labs/huma-dapp#205]
On Goerli network, when attempting to Get Test USDC and prompted to sign message using metamask (w/ hw wallet)

Error: Forbidden Key Path

I think its related to EIP-712 signature support but just a guess.

**Comment by slingncrypto** [comment]
works fine when settings -> prompt is enabled on the device, nvm

**Comment by shan-57blocks** [comment]
Good to know that you found the cause. Will close this issue.
